name: Scala Exercise

on:
  push:
    branches: [ json-exercise-scala ]
  pull_request:
    branches: [ json-exercise-scala ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make compile
